# Generated by Django 3.2.7 on 2021-09-16 16:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='new', max_length=50)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.stock')),
            ],
        ),
    ]
