# Generated by Django 3.2.7 on 2021-09-16 16:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='action',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=50),
        ),
    ]
