# Generated by Django 3.2.7 on 2021-09-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
